name: CI nodeJS
on:
  push:
    branches: [ feature/server ]
jobs:
  ci_to_develop:
    runs-on: ubuntu-latest
    env:
        working-directory: ./server/src
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 14
      - run: npm install
        working-directory: ${{env.working-directory}}
      - run: npm test
        working-directory: ${{env.working-directory}}
        