name: Hello World push

on:
  push:
    branches: [ feature/server ]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Echo Hello World
        run: echo "Hello World"