name: CI push
on:
  push:
    branches: [ feature/server ]
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 14
      - run: cd server
      - run: cd src
      - run: npm install
      - run: npm run test

      
