name: CI node2
on:
  pull_request:
    branches:
    - develop
jobs:
  ci_to_develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@server
      - uses: actions/setup-node@v1
        with: 
          node-version: 14
      - run: cd server
      - run: cd src
      - run: npm ci
      - run: npm run test

      
